# Swiftlint currently still fails, disabled for now
os: osx
language: swift
xcode_project: MarkyMark.xcodeproj
xcode_scheme: markymark_Tests
osx_image: xcode11.3
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod repo update
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/markymark.xcworkspace -scheme markymark-Example -destination 'platform=iOS Simulator,name=iPhone 8' | xcpretty
- swift package generate-xcodeproj
- xcodebuild build -sdk iphoneos -scheme 'Marky-Mark-Package' -project Marky-Mark.xcodeproj
# - pod lib lint
after_success:
  - bash <(curl -s https://codecov.io/bash)
